spring:
  datasource:
    url : jdbc:mysql://localhost:3306/orange
    username : root
    password : 123456
    driverClassName : com.mysql.jdbc.Driver




server:
 port: 8080

# 配置jsp文件的位置，默认位置为：src/main/webapp
#spring.view.prefix:/pages/
spring.mvc.view:
  suffix:.jsp

